### ISSUE TITLE
No controllers

### ISSUE THREAD

**Issue by parijke** [miguelgilmartinez/easyadminTest#1]
There are no controllers, no entities in this repo. Nothing to test here.

**Comment by miguelgilmartinez** [comment]
Fixed. Sorry for the inconveniences. I forgot to commit before uploading.

**Comment by miguelgilmartinez** [comment]
> There are no controllers, no entities in this repo. Nothing to test here.
Fixed. Sorry for the inconveniences. I forgot to commit before uploading.

**Comment by parijke** [comment]
I understand the issue now... btw you forgot easyadmin in the composer.json.

Does it works for you to change to `yield MenuItem::linkToUrl('Father:linktoRoute', 'fa fa-users', '/father');`

**Comment by miguelgilmartinez** [comment]
> I understand the issue now... btw you forgot easyadmin in the composer.json.
> 
> Does it works for you to change to `yield MenuItem::linkToUrl('Father:linktoRoute', 'fa fa-users', '/father');`

Wrong. That third parameter is not a path, it's a 'routeName'

**Comment by parijke** [comment]
I changed to LinktoUrl, so the third is a url now

**Comment by miguelgilmartinez** [comment]
That works.
